### ISSUE TITLE
Display nothing when exporting some special code block

### ISSUE THREAD

**Issue by jack2gs** [coldnew/hexo-renderer-org#22]
Hi @coldnew ,

I found that this module could not work for some org files, which contain some special code blocks.

For example, I'm trying to export this source block
```org
#+BEGIN_SRC csharp
  // Implementing IDisposable.
  class MyResourceWrapper : IDisposable
  {
      // The object user should call this method
      // when they finish with the object.
      public void Dispose()
      {
	  // Clean up unmanaged resources...
	  // Dispose other contained disposable objects...
	  // Just for a test.
	  Console.WriteLine("***** In Dispose! *****");
      }
  }
#+END_SRC
```
The post displays nothing.

But it works for this:
```org
#+BEGIN_SRC csharp
  // Implementing IDisposable.
  class MyResourceWrapper : IDisposable
  {
  }
#+END_SRC
```

The config is
```yml
org:
  cachedir: ./hexo-org-cache/
  htmlize: true
  common: |
    #+OPTIONS: html-postamble:nil
```

If `highlight.js` is used instead of `htmlize`,  it works fine.

Thanks,
Jack

**Comment by hateonion** [comment]
Try add theme field under org

**Comment by coldnew** [comment]
@jack2gs Maybe it's caused by emacs doesn't contains `csharp-mode` by default.

Currently `hexo-renderer-org` use another emacs daemon which will not load user's `~/.emacs.d` config. You should make `hexo-renderer-org` install `csharp-mode` to it's own emacs.

You can find some example here: https://github.com/coldnew/hexo-org-example/blob/master/emacs/init.el#L27

and here: https://github.com/coldnew/hexo-org-example/blob/master/_config.yml#L86

**Comment by jack2gs** [comment]
sorry for late reply. yes, you're right. have solved this problem. thanks.
