### ISSUE TITLE
YAMLException: name of an alias node must contain at least one character at line 11, column 2:

### ISSUE THREAD

**Issue by wolfand11** [coldnew/hexo-renderer-org#9]
when i export my org files, it's appear exception message as below.

```
YAMLException: name of an alias node must contain at least one character at line 11, column 2:
    * Move Sync
```
```org

#+TITLE: Move Sync
#+DATE: <2017-01-06 周五>
#+TAGS: unity, gameplay, network
#+LAYOUT: post
#+CATEGORIES: gameplay 
#+OPTIONS: ^:{}
#+OPTIONS: \n:t
#+OPTIONS: tex:t

* Move Sync

```
"* Move Sync"  is the 11 line

**Comment by coldnew** [comment]
Some of my post has the same issue, I still need time to dig into this situation :(

**Comment by coldnew** [comment]
same issue: https://github.com/CodeFalling/hexo-renderer-org/issues/22

**Comment by wolfand11** [comment]
@coldnew  the error is caused by the separator of org-mode.  when i delete content of "-----" in my blog, the error will dispear.

**Comment by coldnew** [comment]
@wolfand11 yes, I think you are right. it's caused by content of "----".

Still have no method to avoid id :(

**Comment by coldnew** [comment]
Ok, I think I have a workround. It's caused by yaml parser, which will find line start with "---".

To make your content still have "---", you can add `U200B` character, which looks like whitespace but can't really seem by people.

In my emacs, I have following snippet to help insert the `U200B` char:

```elisp
(defun insert-U200B-char ()
  "Insert <U200B> char, this character is nice use in org-mode."
  (interactive)
  (insert "\ufeff"))
```
Just add it before your "---" content.

This issue can't solved by this plugin, since it's happened before renderer.

**Comment by coldnew** [comment]
Actually we can add a filter to modify original file content, but I think it's not a good idea.

Just add a filter like:

```js
hexo.extend.filter.register('before_post_rende', function() {  /*modify file content */  });
```
